// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DrynksMeDBEntities`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=tcp:qdgtj40dep.database.windows.net,1433;Initial Catalog=DrynksDB;User ID=DrynksAdmin;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DrynksMe.DataAccess.Models
{
    /// <summary>
    /// A class which represents the MerchantType table.
    /// </summary>
	[Table("MerchantType")]
	public partial class MerchantType
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string TypeDescription { get; set; }
	}

    /// <summary>
    /// A class which represents the MerchantTag table.
    /// </summary>
	[Table("MerchantTag")]
	public partial class MerchantTag
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int MerchantId { get; set; }
		public virtual int TagId { get; set; }
	}

    /// <summary>
    /// A class which represents the UserMerchantComment table.
    /// </summary>
	[Table("UserMerchantComment")]
	public partial class UserMerchantComment
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? UserId { get; set; }
		public virtual int? MerchantId { get; set; }
		public virtual string Comment { get; set; }
		public virtual bool IsApproved { get; set; }
		public virtual DateTime? CreateDate { get; set; }
		public virtual DateTime? UpdateDate { get; set; }
		public virtual bool IsShared { get; set; }
	}

    /// <summary>
    /// A class which represents the MerchantTypeAssociation table.
    /// </summary>
	[Table("MerchantTypeAssociation")]
	public partial class MerchantTypeAssociation
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int MerchantId { get; set; }
		public virtual int MerchantTypeId { get; set; }
	}

    /// <summary>
    /// A class which represents the Drink table.
    /// </summary>
	[Table("Drink")]
	public partial class Drink
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string DrinkName { get; set; }
		public virtual string DrinkDescription { get; set; }
		public virtual string FoundAt { get; set; }
		public virtual string Origin { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
		public virtual string ImageSmall { get; set; }
		public virtual string ImageLarge { get; set; }
		public virtual string ImageMedium { get; set; }
		public virtual string StandardPicUrl { get; set; }
		public virtual decimal? AlcoholContent { get; set; }
		public virtual bool IsShared { get; set; }
	}

    /// <summary>
    /// A class which represents the User table.
    /// </summary>
	[Table("User")]
	public partial class User
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string FirstName { get; set; }
		public virtual string LastName { get; set; }
		public virtual string MiddleInitial { get; set; }
		public virtual string DeviceId { get; set; }
		public virtual string TwitterId { get; set; }
		public virtual string FacebookId { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
		public virtual string TwitterPicUrl { get; set; }
		public virtual int UserProfileId { get; set; }
		public virtual bool Share { get; set; }
		public virtual string AnonymousSystemId { get; set; }
	}

    /// <summary>
    /// A class which represents the Tag table.
    /// </summary>
	[Table("Tag")]
	public partial class Tag
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string TagName { get; set; }
		public virtual string TagDescription { get; set; }
		public virtual bool? IsAdminGenerated { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
	}

    /// <summary>
    /// A class which represents the DrinkPrice table.
    /// </summary>
	[Table("DrinkPrice")]
	public partial class DrinkPrice
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int DrinkId { get; set; }
		public virtual string Size { get; set; }
		public virtual decimal? RetailPrice { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
	}

    /// <summary>
    /// A class which represents the Merchant table.
    /// </summary>
	[Table("Merchant")]
	public partial class Merchant
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string MerchantName { get; set; }
		public virtual string ProfileName { get; set; }
		public virtual string Description { get; set; }
		public virtual string Location { get; set; }
		public virtual string PrimaryContact { get; set; }
		public virtual string ContactNumber { get; set; }
		public virtual string CustomerNumber { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
		public virtual string ShortVenueInformation { get; set; }
		public virtual string AddressInfo { get; set; }
		public virtual string City { get; set; }
		public virtual string State { get; set; }
		public virtual string Zip { get; set; }
		public virtual string TwitterHandle { get; set; }
		public virtual string Website { get; set; }
		public virtual string VenueType { get; set; }
		public virtual string ImageSmall { get; set; }
		public virtual string ImageLarge { get; set; }
		public virtual string ImageMedium { get; set; }
		public virtual bool IsActive { get; set; }
		public virtual string Email { get; set; }
		public virtual bool IsPremierMerchant { get; set; }
		public virtual decimal? Longitude { get; set; }
		public virtual decimal? Latitude { get; set; }
	}

    /// <summary>
    /// A class which represents the MerchantDrink table.
    /// </summary>
	[Table("MerchantDrink")]
	public partial class MerchantDrink
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int MerchantId { get; set; }
		public virtual int DrinkId { get; set; }
		public virtual bool? IsSignature { get; set; }
	}

    /// <summary>
    /// A class which represents the DrinkUser table.
    /// </summary>
	[Table("DrinkUser")]
	public partial class DrinkUser
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int DrinkId { get; set; }
		public virtual int UserId { get; set; }
		public virtual bool? IsLiked { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
		public virtual string UserNotes { get; set; }
		public virtual bool UserRating { get; set; }
		public virtual string UserUploadedPictureUrl { get; set; }
	}

    /// <summary>
    /// A class which represents the UserTag table.
    /// </summary>
	[Table("UserTag")]
	public partial class UserTag
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int UserId { get; set; }
		public virtual int TagId { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
	}

    /// <summary>
    /// A class which represents the DrinkTag table.
    /// </summary>
	[Table("DrinkTag")]
	public partial class DrinkTag
	{
		[Key]
		public virtual int DrinkTagId { get; set; }
		public virtual int DrinkId { get; set; }
		public virtual int TagId { get; set; }
		public virtual DateTime? CreateDt { get; set; }
		public virtual DateTime? UpdateDt { get; set; }
	}

    /// <summary>
    /// A class which represents the Campaign table.
    /// </summary>
	[Table("Campaign")]
	public partial class Campaign
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int MerchantId { get; set; }
		public virtual bool IsActive { get; set; }
		public virtual DateTime? StartDate { get; set; }
		public virtual DateTime? EndDate { get; set; }
		public virtual string Name { get; set; }
		public virtual string Description { get; set; }
	}

    /// <summary>
    /// A class which represents the UserProfile table.
    /// </summary>
	[Table("UserProfile")]
	public partial class UserProfile
	{
		[Key]
		public virtual int UserId { get; set; }
		public virtual string UserName { get; set; }
		public virtual bool IsActive { get; set; }
	}

}
